### ISSUE TITLE
When running "General" configuration it says "Network not set"

### ISSUE THREAD

**Issue by thomoasis** [brunoolivieri/gradys-simulations#18]
The 'general" configuration says that the "network is not set" and will not run.  This is the code section:

**.wlan[0].radio.displayCommunicationRange = true
#*.visualizer.*.physicalLinkVisualizer.displayLinks = true
#*.visualizer.*.dataLinkVisualizer.displayLinks = true
#*.visualizer.*.networkRouteVisualizer.displayRoutes = true
#*.visualizer.*.*LinkVisualizer.lineShift = 0
#*.visualizer.*.networkRouteVisualizer.lineShift = 0

I understand that the bottom portion is commented out but not sure if that is the issue.  I thought i would ask.

**Comment by Thlamz** [comment]
Hello @thomoasis, thanks for the issue! The "General" configuration only contains very general parameters that apply to all configurations in the *.ini* file. It cannot be run because it does not have the more specific parameters needed for the simulations to run. 

Any other config should work! The "Wifi" and "MAM" configs are base configurations that other ones inherit from, but they contain enough parameters that the simulation should run.

**Comment by thomoasis** [comment]
Thanks!  I have other issues so I will create new ones.  I really appreciate your help.
